// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlyynadhttpyavjcdfyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseXluYWRodHRweWF2amNkZnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzcyMDUsImV4cCI6MjA2NDY1MzIwNX0.0UFzWvuEtniaU1OlbyQdcUF-zrDBcja3N3DjQpm-pNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);